import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path

def plot_learning_curve(metrics: dict, save_path: str | Path | None = None, title: str = "Learning Curve"):
    """
    Plots the learning curve from a metrics dictionary generated by BaseEnv.get_metrics().
    Shows a moving average of the episode rewards.
    """
    rewards = metrics.get("episode_rewards", [])
    if not rewards:
        print("No rewards to plot.")
        return
        
    episodes = np.arange(len(rewards))
    
    # Calculate a simple moving average window of 10% of total episodes (min 5)
    window = max(5, len(rewards) // 10)
    
    # Pad rewards for simple convolution
    pad = np.ones(window-1) * rewards[0]
    padded_rewards = np.concatenate((pad, rewards))
    moving_avg = np.convolve(padded_rewards, np.ones(window)/window, mode='valid')
    
    plt.figure(figsize=(10, 5))
    plt.plot(episodes, rewards, alpha=0.3, color='blue', label='Episode Reward')
    plt.plot(episodes, moving_avg, color='red', linewidth=2, label=f'Moving Average (n={window})')
    
    plt.title(title)
    plt.xlabel('Episode')
    plt.ylabel('Total Reward')
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    
    if save_path:
        plt.savefig(save_path)
        print(f"Plot saved to {save_path}")
    else:
        plt.show()
